# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate data.json syntax
        run: |
          echo "Checking JSON syntax in data.json…"
          jq empty data.json

      - name: Install HTML Tidy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tidy

      - name: Validate HTML files
        run: |
          echo "Running HTML syntax check…"
          tidy -qe control.html user.html parent.html || (echo "HTML errors detected" && exit 1)